name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .github/docker-compose.yml
      SLICK_TEST_DBPATH: slick.dbs.default
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_THREADS: 10
      POSTGRES_MAX_CONNECTIONS: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Starting Testing PostgreSQL Database
      run: docker-compose up -d postgres
    - name: Run tests
      run: sbt test
    - name: Stopping Testing PostgresSQL Database
      run: docker-compose down postgres
